Repository OpenMobileAlliance/lwm2m-registry, pull requests merged in 2019-10, with the labels that each got.

#167 [SEWater] 10313 Gas Reading and RR 6041
  10313.xml
  Common.xml
Labels: Ready for WG Review

#190 [Openlx] 10314 Particulates and RR 6043
  10314.xml
  Common.xml
Labels: bug

#218 [Vaisala] Re-usable resource Measurement Quality Level (6049)
  Common.xml
Labels: Ready for WG Review

#219 [ICA] Manhole Cover - 3408
  3408.xml
Labels: OMNA-Registration

#202 [ICA] - Re-usable Resources - 6044, 6045, 6046, 6047, 6048 submitted
  Common.xml
Labels: Ready for WG Review

#250 [ADMIN] Populate DDF.xml ObjectID 10314 entry
  DDF.xml
Labels: OMNA-Registration, bug
